runtime: python
entrypoint: gunicorn -b :$PORT --worker-class aiohttp.worker.GunicornWebWorker app:app
env: flex
service: socket

runtime_config:
  python_version: 3
liveness_check:
  path: "/liveness_check"    
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
network:
 session_affinity: true
 
handlers:
- url: /.*
  static_dir: /.*
  http_headers:
    Access-Control-Allow-Origin: '*'