runtime: python
entrypoint: gunicorn -b :$PORT --worker-class aiohttp.worker.GunicornWebWorker app:app
env: flex
service: socket

runtime_config:
  python_version: 3
network:
  session_affinity: true
manual_scaling:
  instances: 1
 
handlers:
- url: /.*
  static_dir: /.*
  http_headers:
    Access-Control-Allow-Origin: '*'